from __future__ import annotations

import time

from .ai_album_titles import (
    _album_identity_key,
    _expand_album_title_dependencies,
    _is_album_title_source_candidate,
    _iter_album_cover_sidecars,
    _looks_like_album_title_page,
    _resolve_album_printed_title_hint,
    _resolve_album_title_hint,
)
from .ai_index_analysis import (
    AI_MODEL_MAX_SOURCE_BYTES,
    ArchiveScanOCRAuthority,
    ImageAnalysis,
    _build_caption_metadata,
    _estimate_people_from_detections,
    _get_image_dimensions,
    _merge_people_estimates,
    _prepare_ai_model_image,
    _refresh_detection_model_metadata,
    _resolve_people_count_metadata,
    _run_image_analysis,
    _serialize_people_matches,
)
from .ai_index_runner import (
    DEFAULT_CAST_STORE,
    IMAGE_EXTENSIONS,
    PROCESSOR_SIGNATURE,
    TITLE_PAGE_LOCATION_SOURCE,
    IndexRunner,
    ObjectDetection,
    YOLOObjectDetector,
    _absolute_cli_path,
    _append_geocode_artifact,
    _append_xmp_job_artifact,
    _apply_shard,
    _apply_title_page_location_config,
    _coalesce_archive_processing_files,
    _compute_people_positions,
    _crop_paths_signature,
    _date_estimate_input_hash,
    _dc_date_needs_refresh,
    _dc_date_value,
    _display_work_label,
    _emit_prompt_debug_artifact,
    _explicit_cli_flags,
    _filter_files_by_tree,
    _format_eta,
    _format_location_hint_from_state,
    _format_people_step_label,
    _format_reprocess_reasons,
    _has_dc_date,
    _init_caption_engine,
    _init_date_engine,
    _init_object_detector,
    _init_people_matcher,
    _match_people_with_cast_store_retry,
    _progress_ticker,
    _resolve_caption_prompt,
    _resolve_dc_date,
    _resolve_model_reference,
    _resolve_upstream_page_sidecar_state,
    _settings_signature,
    _sidecar_has_lmstudio_caption_error,
    _sidecar_has_people_to_refresh,
    _write_sidecar_and_record,
    append_job_artifact,
    discover_images,
    main,
    needs_processing,
    parse_args,
    run,
    run_propagate_to_crops,
)
from .ai_index_scan import (
    _bounds_offset,
    _build_dc_source,
    _build_flat_page_description,
    _build_flat_payload,
    _dc_source_needs_refresh,
    _hash_text,
    _layout_payload,
    _page_scan_filenames,
    _resolve_archive_scan_authoritative_ocr,
    _scan_group_paths,
    _scan_group_signature,
    _scan_number,
    _scan_page_key,
)
from .ai_location import (
    _has_legacy_ai_locations_shown_gps,
    _resolve_location_metadata,
    _resolve_location_payload,
    _resolve_locations_shown,
)
from .ai_sidecar_state import (
    MIN_EXISTING_SIDECAR_BYTES,
    _compute_xmp_title,
    _effective_sidecar_location_payload,
    _effective_sidecar_ocr_text,
    _resolve_xmp_text_layers,
    has_current_sidecar,
    has_valid_sidecar,
)
